In [ ]:
import numpy as np

In [ ]:
import numpy as np
array=np.zeros(10)
print("An array of 10 zeros:")
print(array)


An array of 10 zeros:
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
array=np.ones(10)
print("An array of 10 ones:")
print(array)


An array of 10 ones:
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [ ]:
import numpy as np
array=np.ones(10)*5
print("An array of 10 fives:")
print(array)


An array of 10 fives:
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [ ]:
import numpy as np
array= list(range(10, 50))
print(array)


[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]


In [ ]:
import numpy as np
array=np.arange(10,51,2)
print("Array of all the even integers from 10 to 50")
print(array)


Array of all the even integers from 10 to 50
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [ ]:
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
import numpy as np
x = np.eye(3)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
rand_num = np.random.normal(0,1,1)
print("Random number between 0 and 1:")
print(rand_num)

Random number between 0 and 1:
[-1.54220859]


In [ ]:
import numpy as np
rand_num = np.random.normal(0,1,25)
print("25 random numbers from a standard normal distribution:")
print(rand_num)

25 random numbers from a standard normal distribution:
[-0.03188122  2.09075194 -1.63394096 -0.81226239 -1.1134966  -0.66447794
  0.21148804  0.96586499 -0.36228519 -2.36531269 -1.04953862  0.58577165
 -0.0880661   0.99394877  0.26118427  1.66999981  1.5464349   1.02552677
 -0.93473119  0.55289371 -1.14524029  0.66655247  2.00613493 -0.4544926
  0.76306899]


In [ ]:
import numpy as np
x =  np.arange(0.01, 1.01, 0.01).reshape(10,10)
print(x)

[[0.01 0.02 0.03 0.04 0.05 0.06 0.07 0.08 0.09 0.1 ]
 [0.11 0.12 0.13 0.14 0.15 0.16 0.17 0.18 0.19 0.2 ]
 [0.21 0.22 0.23 0.24 0.25 0.26 0.27 0.28 0.29 0.3 ]
 [0.31 0.32 0.33 0.34 0.35 0.36 0.37 0.38 0.39 0.4 ]
 [0.41 0.42 0.43 0.44 0.45 0.46 0.47 0.48 0.49 0.5 ]
 [0.51 0.52 0.53 0.54 0.55 0.56 0.57 0.58 0.59 0.6 ]
 [0.61 0.62 0.63 0.64 0.65 0.66 0.67 0.68 0.69 0.7 ]
 [0.71 0.72 0.73 0.74 0.75 0.76 0.77 0.78 0.79 0.8 ]
 [0.81 0.82 0.83 0.84 0.85 0.86 0.87 0.88 0.89 0.9 ]
 [0.91 0.92 0.93 0.94 0.95 0.96 0.97 0.98 0.99 1.  ]]


In [ ]:
mat = np.arange(1,26).reshape(5,5)
print(mat)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
import numpy as np
a = np.arange(1,26).reshape(5,5)
print("Old masssiv")
print(a)
a = np.delete(a, [0, 1], 0)
a = np.delete(a, 0, 1)
print("New masssiv")
print(a)


Old masssiv
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
New masssiv
[[12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]


In [ ]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
x=np.sum(mat)
print("Result is:")
print(x)


Result is:
325


In [ ]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
x=np.std(mat)
print("Standard deviation in the starting matrix mat is:")
print(x)

Standard deviation in the starting matrix mat is:
7.211102550927978


In [ ]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
x=np.sum(mat, axis=0)
print("The sum of the values in the columns in the starting matrix mat is:")
print(x)

The sum of the values in the columns in the starting matrix mat is:
[55 60 65 70 75]


In [ ]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print("Old masssiv")
print(mat)
mat = np.delete(mat, [0, 1, 2, 3], 1)
mat = np.delete(mat, [0, 1, 2, 4], 0)
print("New masssiv")
print(mat)


Old masssiv
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
New masssiv
[[20]]


In [ ]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print("Old masssiv")
print(mat)
mat = np.delete(mat, [0, 2, 3, 4], 1)
mat = np.delete(mat, [3, 4], 0)
print("New masssiv")
print(mat)


Old masssiv
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
New masssiv
[[ 2]
 [ 7]
 [12]]


In [ ]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print("Old masssiv")
print(mat)
mat = np.delete(mat, [0, 1, 2, 3], 0)
print("New masssiv")
print(mat)


Old masssiv
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
New masssiv
[[21 22 23 24 25]]


In [ ]:
import numpy as np
mat = np.arange(1,26).reshape(5,5)
print("Old masssiv")
print(mat)
mat = np.delete(mat, [0, 1, 2], 0)
print("New masssiv")
print(mat)


Old masssiv
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
New masssiv
[[16 17 18 19 20]
 [21 22 23 24 25]]
